```{r}
library(terra)
```

Load the data into R. Right now, I have higher resolution data stored in a 
folder in sandbox/data. These files can be recalculated from the 
00_generate_elev_derivatives script. 


```{r}
data_path <- "\\\\Mac/Home/Documents/terrainworks/code/sandbox/data/"

elev <- rast(file.path(data_path, "elev_scottsburg.flt"))
grad <- rast(file.path(data_path, "grad_15.flt"))
plan <- rast(file.path(data_path, "plan_15.flt"))
prof <- rast(file.path(data_path, "prof_15.flt"))
norm <- rast(file.path(data_path, "norm_15.flt"))
tan <- rast(file.path(data_path, "tan_15.flt"))
pca <- rast(file.path(data_path, "pca_k1_d5.flt"))

#calculate mean slopes
mean <- (norm + tan) / 2
names(mean) <- "mean_15"

vars_raster <- c(
  grad,
  plan,
  prof,
  norm, 
  tan, 
  mean,
  pca
)

initiation_points <- vect(file.path(data_path, "initiation_points.shp"))

```

Plot elev + initiation points

```{r}
plot(elev)
points(initiation_points)
```

Create buffers around the initiation points to build our negative region. 

```{r}
neg_region <- make_neg_region(initiation_points, 
                vars_raster, 
                inner_buffer = 11, 
                outer_buffer = 150)

analysis_mask <- create_analysis_region_mask(raster = vars_raster, 
                                             points = initiation_points)

```

```{r}

plot(elev)
points(initiation_points)
# plot(analysis_mask, add = TRUE, col = rgb(.2, .2, .2, alpha = .6))
# polys(as.polygons(neg_region))
plot(terra::mask(neg_region, analysis_mask), add = TRUE, col = rgb(.2, .2, .2, alpha = .5))

```


Sample negative points

```{r}
training_points <- sample_negative_points(
    positive_points = initiation_points,
    analysis_region = analysis_mask,
    buffer = TRUE,
    buffer_radius = 11,
    negative_proportion = 1., 
    rseed = 2
  )
```


```{r}
plot(elev)
plot(analysis_mask, add = TRUE)
points(training_points, col = ifelse(training_points$class == "positive", 
                                    "black", 
                                    "red"))
```

Next, extract the values and put them into a training data frame. 
```{r}
training_data <- extract_values(
    raster = vars_raster,
    points = training_points,
    extraction_method = "centroid",
    extraction_layer = NULL,
    xy = FALSE
  )
```

