# Evaluate the model for sensitivity to a parameter

Change these as needed for the data that you want to use.  
```{r}

dem_path = "//Mac/Home/Documents/terrainworks/code/sandbox/data/DeanCr/elev_deancr.flt"  
init_path = "//Mac/Home/Documents/terrainworks/code/sandbox/data/DeanCr/DeanCr_Initiation_Points.shp" 
out_path = "//Mac/Home/Documents/terrainworks/code/sandbox/data/scratch/deancr/"

```

Choose the parameter to evaluate. 
Here, we will look at the negative region buffer value. 

```{r}
# Target parameter: negative region buffer
values = c(50, 150, 500, 1000)

success_curves = list()
```

Now, run dem_to_model with each possible value and store the success rate curves
to compare. 

```{r}

for (value in values) {
  model <- dem_to_model(dems = dem_path, 
                        initiation_points = init_path, 
                        output_dir = out_path, 
                        neg_region_buffer = value)
  
  alldata <- as.data.frame(rast(dem_path))
  
  prob_rast <- make_prob_raster(model = model,
                                data = alldata)
  
  success_curve <- append(success_curve, generate_success_curve(
                                              predicted_raster = prob_raster, 
                                              initiation_points = vect(init_path), 
                                              step_size = 0.5, 
                                              plot = FALSE))
}

```

